services:

  postgres:
    image: postgres:16
    container_name: financasapi_postgres
    restart: always
    environment:
      POSTGRES_DB: financasdb
      POSTGRES_USER: financasuser
      POSTGRES_PASSWORD: financaspass
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: financasapi_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: financasapi_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog
    container_name: financasapi_mailhog
    restart: always
    ports:
      - "1025:1025"   # Porta SMTP
      - "8025:8025"   # Interface web do MailHog

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
